[package]
name = "rt-mem-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raw_sync = "*"
shared_memory = "*"
env_logger = "*"
command-fds = "0.3.0"
libc = "0.2.153"
csv = "1.1"